import {grades,stoneFieldGrades,earlyGrades,sections,slotsForGrade,ageEligibility} from './booking-rules.js';
import {mountCaptcha} from './captcha.js';
(()=>{
 const $=id=>document.getElementById(id);let grade=stoneFieldGrades[0],section=sections[0],selected='',approved=new Map(),pending=new Map(),reserved=new Map(),capacity=30,ready=false,busy=false,generation=0,requestId='',requestPayload='',campus='stonefield';
 const captcha=mountCaptcha($('booking-captcha'),'booking'),form=$('booking-form');
 function choices(root,name,values,selectedValue){root.replaceChildren();values.forEach(value=>{const label=document.createElement('label');label.className='booking-option';const input=document.createElement('input');input.type='radio';input.name=name;input.value=value;input.checked=value===selectedValue;input.required=true;const span=document.createElement('span');span.textContent=value;if(name==='section'){const small=document.createElement('small');small.textContent=`${capacityForGrade(grade)} children each`;span.append(small);}label.append(input,span);root.append(label);});}
 const capacityForGrade=value=>slotsForGrade(value).length;
 function renderSections(){choices(document.querySelector('.section-choices'),'section',sections,section);}
 function renderGrades(nextCampus){campus=nextCampus;const values=campus==='kidsverse'?earlyGrades:stoneFieldGrades;if(!values.includes(grade))grade=values[0];choices(document.querySelector('.grade-choices'),'grade',values,grade);document.querySelectorAll('.grade-tab').forEach(button=>{const active=button.dataset.campus===campus;button.classList.toggle('is-active',active);button.setAttribute('aria-pressed',String(active));});$('grade-campus-note').textContent=campus==='kidsverse'?'Kidsverse School · Playway, Nursery, L.K.G and U.K.G · 3 sections with 20 children each. Minimum ages by 31 March 2027: 2, 3, 4 and 5 years respectively.':'Stone Field International School · Planned opening grades Grade 1 to Grade 5.';capacity=capacityForGrade(grade);renderSections();}
 renderGrades(campus);
 document.querySelectorAll('.grade-tab').forEach(button=>button.addEventListener('click',()=>renderGrades(button.dataset.campus)));
 document.querySelector('.grade-choices').addEventListener('change',event=>{if(event.target.name!=='grade')return;grade=event.target.value;capacity=capacityForGrade(grade);renderSections();});
 document.querySelector('.section-choices').addEventListener('change',event=>{if(event.target.name==='section')section=event.target.value;});
 const grid=$('slot-grid');for(const row of ['A','B','C']){const line=document.createElement('div');line.className='slot-row';line.dataset.row=row;const label=document.createElement('strong');label.className='row-name';label.textContent=row;line.append(label);for(let i=0;i<5;i++){const bench=document.createElement('div'),top=document.createElement('div'),places=document.createElement('div');top.className='bench-top';top.setAttribute('aria-hidden','true');places.className='bench-places';for(let j=1;j<=2;j++){const slot=row+(i*2+j),button=document.createElement('button');button.className='slot-button';button.type='button';button.dataset.slot=slot;button.setAttribute('aria-pressed','false');button.disabled=true;button.addEventListener('click',()=>{if(!ready||busy||approved.has(slot)||reserved.has(slot))return;selected=slot;update();captcha.ensure();});places.append(button);}bench.append(top,places);line.append(bench);}grid.append(line);}
 const buttons=[...grid.querySelectorAll('button')];
 function checkAge(showAlert=false){const input=form.elements.dob;input.setCustomValidity('');if(!input.value){const earlyMinimum=earlyGrades.indexOf(grade)+2;$('age-guidance').textContent=earlyMinimum>1?`${grade}: at least ${earlyMinimum} completed years on 31 March 2027.`:`${grade}: at least ${Number(grade.slice(-1))+5} completed years on 31 March 2027.`;return false;}const rule=ageEligibility(input.value,grade);$('age-guidance').textContent=rule.message;$('age-guidance').classList.toggle('error',!rule.eligible);if(!rule.eligible){input.setCustomValidity(rule.message);if(showAlert)window.alert(rule.message);}return rule.eligible;}
 form.elements.dob.max=new Date().toISOString().slice(0,10);form.elements.dob.addEventListener('change',()=>checkAge(true));
 function update(){const validSlots=new Set(slotsForGrade(grade));buttons.forEach(b=>{const slot=b.dataset.slot,name=approved.get(slot),reservedLabel=reserved.get(slot),count=pending.get(slot)||0;b.hidden=!validSlots.has(slot);b.disabled=!ready||busy||!validSlots.has(slot)||approved.has(slot)||reserved.has(slot);b.classList.toggle('has-pending',count>0);b.classList.toggle('is-approved',approved.has(slot));b.classList.toggle('is-reserved',reserved.has(slot));b.setAttribute('aria-pressed',String(slot===selected));b.replaceChildren();const number=document.createElement('strong');number.textContent=slot;b.append(number);if(reservedLabel){const tag=document.createElement('small');tag.className='reserved-name';tag.textContent=reservedLabel;b.append(tag);}if(name){const child=document.createElement('small');child.className='approved-name';child.textContent=name;b.append(child);}if(count){const note=document.createElement('small');note.className='pending-count';note.textContent=`${count} pending approval`;b.append(note);}b.setAttribute('aria-label',`${slot}, ${reservedLabel?'reserved for '+reservedLabel:name?'approved for '+name:slot===selected?'selected':'available'}${count?', '+count+' pending approval':''}`);});$('booking-fields').disabled=!selected||!ready||busy;$('selected-summary').textContent=selected?`${grade} · ${section} · ${selected}`:'Choose an available number';$('details-help').textContent=selected?'Your request will be reviewed by the SFIS team.':'Select a number to unlock the form.';for(const [id,current] of [['choose-progress',!selected],['family-progress',!!selected]]){if(current)$(id).setAttribute('aria-current','step');else $(id).removeAttribute('aria-current');}$('room-badge').textContent=approved.size+reserved.size>=capacity?'Fully allocated':approved.size+reserved.size>=Math.ceil(capacity*2/3)?'Filling fast':'Requests open';}
 async function availability(force=false){if((busy&&!force)||$('room-step').hidden)return;const token=++generation;try{const res=await fetch('/api/bookings?'+new URLSearchParams({grade,section}),{cache:'no-store',signal:AbortSignal.timeout(20000)});const data=await res.json();if(token!==generation)return;if(!res.ok)throw Error(data.error||'Unable to load availability.');approved=new Map(data.approved.map(r=>[r.slot,r.name]));pending=new Map(data.pending.map(r=>[r.slot,r.count]));reserved=new Map((data.reserved||[]).map(r=>[r.slot,r.label]));capacity=data.capacity;ready=true;if(selected&&(approved.has(selected)||reserved.has(selected))){selected='';$('booking-status').textContent='This number is no longer available. Please choose another.';}$('availability-status').textContent=approved.size+reserved.size>=capacity?'This section is fully allocated. Please choose another section.':'Pending requests do not reserve a number. KVS student reservations are marked on the classroom map.';$('availability-status').className='';$('retry-availability').hidden=true;}catch(e){if(token!==generation)return;ready=false;$('availability-status').textContent=e.name==='TimeoutError'?'Availability timed out. Please retry.':e.message;$('availability-status').className='error';$('retry-availability').hidden=false;}update();}
 $('classroom-choice').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target);grade=data.get('grade');section=data.get('section');selected='';ready=false;approved.clear();pending.clear();reserved.clear();$('grade-summary').textContent=grade;$('section-summary').textContent='Section '+section;$('grade-step').hidden=true;$('booking-intro').hidden=true;$('room-step').hidden=false;$('availability-status').textContent='Loading availability…';update();checkAge(!!form.elements.dob.value);$('room-title').focus();availability();});
 $('change-class').addEventListener('click',()=>{if(busy)return;generation++;$('room-step').hidden=true;$('grade-step').hidden=false;$('booking-intro').hidden=false;document.querySelector('[name=grade]:checked').focus();});$('retry-availability').addEventListener('click',availability);setInterval(availability,15000);window.addEventListener('focus',availability);
 form.addEventListener('submit',async e=>{e.preventDefault();if(busy||!ready||!selected)return;if(!checkAge(true)||!form.reportValidity())return;
 const captchaData=captcha.values();if(!captchaData.captchaId){$('booking-status').textContent='Please load and complete the CAPTCHA.';return;}
 if(!window.confirm('By submitting this booking request, you agree to receive a call from the SFIS team. Please enter a correct mobile number. Requests with an incorrect number will be rejected.\n\nYour request remains pending until the school approves it. Submit your request?'))return;
 const data=Object.fromEntries(new FormData(form));data.consent=form.elements.consent.checked;Object.assign(data,{grade,section,slot:selected});const signature=JSON.stringify(data);if(signature!==requestPayload){requestId=crypto.randomUUID();requestPayload=signature;}Object.assign(data,{requestId,...captchaData});busy=true;generation++;update();$('book-submit').textContent='Submitting request…';$('change-class').disabled=true;const status=$('booking-status');status.className='';status.textContent='Saving securely…';let saved=false;
 try{const res=await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data),signal:AbortSignal.timeout(25000)});const result=await res.json();if(!res.ok){if(result.code==='SLOT_TAKEN'||result.code==='SLOT_RESERVED'){selected='';await availability(true);}throw Error(result.error||'Unable to submit your request. Please retry.');}if(!result.saved||!result.reference)throw Error('We could not confirm the request. Please retry.');saved=true;$('room-step').hidden=true;$('booking-success').hidden=false;$('booking-thanks').textContent=`Thank you. Your request for ${data.childName} is ${result.status}.`;$('receipt-class').textContent=`Requested: ${grade} · Section ${section} · ${data.slot}`;$('booking-reference').textContent=result.reference;form.reset();$('booking-success').focus();}catch(error){status.className='error';status.textContent=error.name==='TimeoutError'?'The connection timed out. Complete a new CAPTCHA and retry; your request will not be saved twice.':error.message;status.focus();}finally{busy=false;$('book-submit').textContent='Submit booking request →';$('change-class').disabled=false;update();if(!saved)await captcha.refresh();}});
 $('copy-booking-id').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('booking-reference').textContent);$('copy-status').textContent='Booking ID copied.';}catch{$('copy-status').textContent='Select and copy the booking ID above.';}});
})();
