const $=s=>document.querySelector(s),message=$('#message');let page=1,loading=false,sequence=0,appliedFilters=new URLSearchParams();
let bookingSequence=0;
const statuses={new:'New',contacted:'Contacted',discussion:'Family discussion',admitted:'Admitted',closed:'Closed'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>new Date(v).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kolkata'});
function signedIn(yes){$('#login').hidden=yes;$('#dashboard').hidden=!yes;$('#logout').hidden=!yes;if(!yes){bookingSequence++;$('#booking-stats').replaceChildren();$('#classroom-bookings').replaceChildren();$('#bookings-status').textContent='';$('#leads').replaceChildren();$('#stats').replaceChildren();$('#grade-counts').replaceChildren();}}
async function api(method='GET',body,query=''){const r=await fetch('/api/founders'+query,{method,credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok){if(r.status===401&&method!=='POST')signedIn(false);throw Error(data.error||'Please try again.');}return data;}
async function load(){const seq=++sequence;loading=true;$('#refresh').disabled=true;message.textContent='';try{const query=new URLSearchParams(new FormData($('#filters')));query.set('page',page);const data=await api('GET',null,'?'+query);if(seq!==sequence)return;appliedFilters=new URLSearchParams(query);appliedFilters.delete('page');signedIn(true);loadBookings();$('#stats').innerHTML=[['All enquiries',data.summary.total],['New enquiries',data.summary.new],['Following up',data.summary.following_up],['Admitted',data.summary.admitted]].map(([label,value])=>`<div class="stat"><span>${label}</span><strong>${value}</strong></div>`).join('');$('#count').textContent=`${data.total} matching enquiries`;$('#page').textContent=`Page ${page} of ${Math.max(1,Math.ceil(data.total/30))}`;$('#prev').disabled=page<=1;$('#next').disabled=page*30>=data.total;
$('#grade-counts').innerHTML=(data.gradeCounts||[]).map(row=>`<div><strong>${esc(row.grade)} <span>${esc(row.count)}</span></strong><small>${esc(row.enquiryType)}</small></div>`).join('');
$('#leads').innerHTML=data.leads.length?data.leads.map(l=>`<details class="lead"><summary><div><strong>${esc(l.child_name)}</strong><small>${esc(l.parent_name)} · ${esc(l.upcoming_grade)} · ${esc(date(l.created_at))} IST</small></div><span class="badge">${esc(statuses[l.status]||l.status)}</span></summary><div class="details"><div><dl>${[['Parent / guardian',l.parent_name],['Mobile',l.mobile],['Locality',l.locality],['Campus',['Playway','Nursery','LKG','UKG'].includes(l.upcoming_grade)?'Kidsverse Campus — early years enquiry':'Stone Field — opening-grade interest (not confirmed)'],['Upcoming grade',l.upcoming_grade],['Current grade',l.current_grade],['Current school',l.current_school],['Kidsverse student',l.kidsverse_student?'Yes':'No'],['Last updated',date(l.updated_at)+' IST']].map(([k,v])=>`<dt>${k}</dt><dd>${esc(v)}</dd>`).join('')}</dl><div class="actions"><a href="tel:+91${esc(l.mobile)}">Call parent ↗</a><a href="https://wa.me/91${esc(l.mobile)}" target="_blank" rel="noopener noreferrer">WhatsApp ↗</a></div></div><form class="edit" data-id="${esc(l.id)}"><label>Follow-up status<select name="status">${Object.entries(statuses).map(([k,v])=>`<option value="${k}" ${k===l.status?'selected':''}>${v}</option>`).join('')}</select></label><label>Private founder notes<textarea name="notes" maxlength="2000" placeholder="Discussion notes and next steps">${esc(l.founder_notes)}</textarea></label><button class="gold">Save follow-up</button></form></div></details>`).join(''):'<p class="empty">No enquiries match these filters.</p>';
}catch(e){if(seq===sequence)message.textContent=e.message;}finally{loading=false;$('#refresh').disabled=false;}}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;message.textContent='';try{await api('POST',{passcode:$('#passcode').value});$('#passcode').value='';page=1;await load();}catch(e){message.textContent=e.message;}finally{b.disabled=false;}});
$('#logout').addEventListener('click',async()=>{try{await api('DELETE');sequence++;signedIn(false);message.textContent='Signed out.';}catch(e){message.textContent=e.message;}});
$('#filters').addEventListener('submit',e=>{e.preventDefault();page=1;load();});$('#refresh').addEventListener('click',()=>load());$('#prev').addEventListener('click',()=>{if(!loading){page--;load();}});$('#next').addEventListener('click',()=>{if(!loading){page++;load();}});
$('#leads').addEventListener('submit',async e=>{if(!e.target.matches('.edit'))return;e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{await api('PATCH',{id:e.target.dataset.id,...Object.fromEntries(new FormData(e.target))});await load();message.textContent='Follow-up saved.';}catch(e){message.textContent=e.message;}finally{b.disabled=false;}});
load();

$('#export-leads').addEventListener('click',async()=>{
 const button=$('#export-leads');button.disabled=true;message.textContent='';
 try{const query=new URLSearchParams(appliedFilters);query.set('export','csv');const response=await fetch('/api/founders?'+query,{credentials:'same-origin'});
 if(!response.ok){if(response.status===401)signedIn(false);const result=await response.json();throw Error(result.error||'Export failed.');}
 const url=URL.createObjectURL(await response.blob());const link=document.createElement('a');link.href=url;link.download='sfis-grade-enquiries.csv';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);message.textContent='Grade export downloaded.';
 }catch(error){message.textContent=error.message;}finally{button.disabled=false;}
});


function bookingQuery(){const q=new URLSearchParams(new FormData($('#booking-filters')));q.set('view','bookings');return q;}
async function loadBookings(){const seq=++bookingSequence;const button=$('#load-bookings');button.disabled=true;$('#bookings-status').textContent='Loading booking requests…';try{const data=await api('GET',null,'?'+bookingQuery());if(seq!==bookingSequence)return;$('#booking-stats').innerHTML=[['All requests',data.summary.total],['Pending review',data.summary.pending],['Approved',data.summary.approved],['Rejected',data.summary.rejected]].map(([label,n])=>`<div class="stat"><span>${esc(label)}</span><strong>${esc(n)}</strong></div>`).join('');$('#bookings-status').textContent=`${data.bookings.length} matching requests`;$('#classroom-bookings').innerHTML=data.bookings.map(b=>`<details class="lead"><summary><div><strong>${esc(b.child_name)}</strong><small>${esc(b.grade)} · Requested ${esc(b.section)} / ${esc(b.slot)}${b.status==='approved'?` · Assigned ${esc(b.assigned_section)} / ${esc(b.assigned_slot)}`:''}</small></div><span class="badge">${esc(b.status)}</span></summary><div class="details"><dl>${[['Booking ID',b.booking_code||b.id],['Date of birth',b.child_dob],['Age on 31 March 2027',b.eligibility.age+' completed years'],['Eligibility',b.eligibility.minimum===null?b.eligibility.message:b.eligibility.eligible?'Eligible':b.eligibility.message],['Father',b.father_name],['Mother',b.mother_name],['Location',b.locality],['Mobile',b.mobile],['Submitted',date(b.created_at)],['Reviewed',b.reviewed_at?date(b.reviewed_at):'Awaiting review'],...(b.rejection_reason?[['Rejection reason',b.rejection_reason]]:[])].map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl>${b.status!=='rejected'?`<form class="booking-review" data-booking-id="${esc(b.id)}"><p>${b.status==='approved'?'Rejecting this approved request releases its allocation and allows a new request from this mobile number.':'Approve to assign an available number. If every section in this grade is full, the request stays pending.'}</p><label>Reason for rejection<textarea name="reason" maxlength="1000" placeholder="Required when rejecting a request"></textarea></label><div class="booking-review-actions">${b.status==='pending'?`<button class="gold" type="submit" name="decision" value="approve" ${b.eligibility.eligible?'':'disabled'}>Approve & assign</button>`:''}<button type="submit" name="decision" value="reject">Reject request</button></div></form>`:'<p>This rejected request is kept for your records. The family can submit a fresh request.</p>'}</div></details>`).join('')||'<p>No booking requests match these filters.</p>';}catch(e){if(seq===bookingSequence)$('#bookings-status').textContent=e.message;}finally{button.disabled=false;}}
$('#load-bookings').addEventListener('click',loadBookings);
$('#booking-filters').addEventListener('submit',e=>{e.preventDefault();loadBookings();});
$('#classroom-bookings').addEventListener('submit',async e=>{if(!e.target.matches('.booking-review'))return;e.preventDefault();const form=e.target,decision=e.submitter?.value,reason=form.elements.reason.value.trim();if(decision==='reject'&&reason.length<3){form.elements.reason.setCustomValidity('Enter a reason of at least 3 characters.');form.elements.reason.reportValidity();return;}form.elements.reason.setCustomValidity('');if(!confirm(decision==='approve'?'Approve this request and assign an available number in the same grade?':'Reject this request? Its mobile number will be allowed to apply again.'))return;const buttons=[...form.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{const result=await api('PATCH',{type:'booking',id:form.dataset.bookingId,decision,reason});await loadBookings();$('#bookings-status').textContent=result.status==='approved'?`Approved. Assigned Section ${result.section}, number ${result.slot}.`:'Request rejected. This mobile number can submit a new request.';}catch(e){$('#bookings-status').textContent=e.message;buttons.forEach(b=>b.disabled=false);}});
$('#classroom-bookings').addEventListener('input',e=>{if(e.target.name==='reason')e.target.setCustomValidity('');});
$('#export-bookings').addEventListener('click',async()=>{const button=$('#export-bookings');button.disabled=true;try{const q=bookingQuery();q.set('export','csv');const r=await fetch('/api/founders?'+q);if(!r.ok){if(r.status===401)signedIn(false);const data=await r.json();throw Error(data.error||'Unable to export.');}const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download='sfis-classroom-bookings.csv';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){$('#bookings-status').textContent=e.message;}finally{button.disabled=false;}});

function renderReservations(rows){const form=$('#reservation-form'),grade=form.elements.grade.value,section=form.elements.section.value,chosen=rows.filter(r=>r.grade===grade&&r.section===section);form.elements.count.max=['Playway','Nursery','L.K.G','U.K.G'].includes(grade)?20:30;form.elements.count.value=chosen.length;$('#booking-reservations').innerHTML=rows.length?`<strong>Currently reserved</strong><div>${rows.map(r=>`<span>${esc(r.grade)} · ${esc(r.section)} / ${esc(r.slot)} — ${esc(r.label)}</span>`).join('')}</div>`:'<p>No KVS student places are currently reserved.</p>';$('#booking-reservations').dataset.rows=JSON.stringify(rows);}
$('#reservation-form').addEventListener('change',e=>{if(e.target.tagName!=='SELECT')return;const rows=JSON.parse($('#booking-reservations').dataset.rows||'[]');renderReservations(rows);});
$('#reservation-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.target,button=form.querySelector('button'),data=Object.fromEntries(new FormData(form));data.count=Number(data.count);if(!Number.isInteger(data.count)||data.count<0||data.count>Number(form.elements.count.max)){form.elements.count.reportValidity();return;}const old=JSON.parse($('#booking-reservations').dataset.rows||'[]').filter(r=>r.grade===data.grade&&r.section===data.section).length;const verb=data.count<old?'release':'reserve';if(!confirm(data.count===0?'Release all KVS student reservations for this grade and section?':`Set ${data.count} KVS student reservations for ${data.grade}, ${data.section}? This may ${verb} classroom reference numbers.`))return;button.disabled=true;$('#reservation-status').textContent='Saving reservation count…';try{const result=await api('PATCH',{type:'bookingReservation',...data});renderReservations(result.reservations||[]);$('#reservation-status').textContent=result.count===0?`All KVS reservations released for ${data.grade}, ${data.section}.`:`${result.count} places reserved for KVS students in ${data.grade}, ${data.section}.`;await loadBookings();}catch(error){$('#reservation-status').textContent=error.message;}finally{button.disabled=false;}});

$('#release-reservations').addEventListener('click',()=>{const form=$('#reservation-form');form.elements.count.value='0';form.requestSubmit();});
